version: '3.8'
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    pull_policy: always
    init: true
    stop_grace_period: 5s
    expose:
    - 5432
    ports:
    - 5432:5432
    privileged: false
    volumes:
    - /home/maks/postgres/data:/var/lib/postgresql/data:rw
    - /home/maks/postgres/backups:/backups:rw
    # networks:
    #   default:
    #     ipv4_address: 172.28.0.2
# networks:
#   default:
#     name: expero
#     ipam:
#       driver: default
#       config:
#       - subnet: 172.28.0.0/15
